version: '3'

services:
  backend:
    container_name: 'backend'
    build: ./backend
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '4000:3000'
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=kupipodariday
      - PGDATA=/var/lib/postgresql/data/pgdata
    depends_on:
      - database

  database:
    container_name: 'db'
    image: postgres:12-alpine
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=kupipodariday
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata/kupipodariday

volumes:
  pg_data:
    driver: local

networks:
  backend:
