version: '3'

services:
  db:
    container_name: 'db'
    image: postgres:12-alpine
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  backend:
    container_name: 'backend'
    build: ./backend
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '4000:3000'
    depends_on:
      - database
  frontend:
    container_name: 'frontend'
    build: ./frontend
    restart: unless-stopped
    ports:
      - '8081:80'
volumes:
  pg_data:
    driver: local

networks:
  backend:
